stages:
  - stage:
    displayName: Build
    jobs:
      - job: A
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: echo 'Job A'
      - job: B
        dependsOn: A
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: echo 'Job B'
