# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  - group: common-variables

steps:
- script: |
    echo "User = $(username)"
    echo "Password = $(password)"
  displayName: 'Run a multi-line script'
