trigger:
- none

pool:
  vmImage: ubuntu-latest

# variables:
#   - group: common-variables

steps:

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure DevOps To Portal Connection'
    KeyVaultName: 'avanade-secret-1'
    SecretsFilter: '*'
    RunAsPreJob: false

- script: |
    echo "User = $(username)"
    echo "Password = $(password)"
  displayName: 'Run a multi-line script'